import { ThemeProvider } from "@/components/theme-provider";
import SearchProvider from "@/providers/SearchProvider";
import { Inter } from "next/font/google";
import { Toaster } from "sonner";
import "../app/globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        <SearchProvider>
          <ThemeProvider
            attribute="class"
            defaultTheme="dark"
            enableSystem
            disableTransitionOnChange
          >
            {children}
            <Toaster theme="system" />
          </ThemeProvider>
        </SearchProvider>
      </body>
    </html>
  );
}
