import Navbar from "@/components/navbar";
import "../globals.css";

export const metadata = {
  title: "Voyagp | Authentications",
  description: "Generated by create next app",
};

export default function AuthLayout({ children }: { children: React.ReactNode }) {
  return (
    <>
      <Navbar isLandingPage={false} showSideMenu={false} />
      <main>{children}</main>
    </>
  );
}
